[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bay_attendance_check = "HW4UmSnJfLd8yn8afM3WGz2w52ea7i1oTGqCSAXJmwv5"

[programs.devnet]
bay_attendance_check = "HW4UmSnJfLd8yn8afM3WGz2w52ea7i1oTGqCSAXJmwv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
